//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ads.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int Id { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string BackgroungColor { get; set; }
        public string BackgroundImage { get; set; }
        public string Logo { get; set; }
        public string ButtonText { get; set; }
        public string PriceFormat { get; set; }
        public string TitleColor { get; set; }
        public string PriceColor { get; set; }
        public string ButtonColor { get; set; }
    }
}
